# -*- coding: utf-8 -*-
"""PYTHON - DF Mod 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XdfrZb270RigDXF_GmazpE0OXRSy2JTg

#Resolução do Desafio - Bootcamp Python - Módulo 2

## By Keila Freitas
"""

#importando Bibliotecas
import numpy as np
import pandas as pd

df = pd.read_csv("https://pycourse.s3.amazonaws.com/bike-sharing.csv")

"""a. Qual o tamanho desse dataset?"""

df.info()

"""R.: 17379 linhas, com 17 colunas. Não há valores nulos.

b. Qual a média da coluna windspeed?
"""

df['windspeed'].describe()

"""R.: 0,190098

c. Qual a média da coluna temp?
"""

df['temp'].describe()

"""R.: 0,496987

d. Quantos registros existem para o ano de 2011?
"""

#Indexação booleana
cond_11 = (df.datetime >= '2011-01-01') & (df.datetime <= '2011-12-31')
df[cond_11].info()
#df.head()

"""R.: 8645 registros.

e. Quantos registros existem para o ano de 2012?
"""

cond_12 = (df.datetime >= '2012-01-01') & (df.datetime <= '2012-12-31')
df[cond_12].info()

"""R.: 8734 registros.

f. Quantas locações de bicicletas foram efetuadas em 2011?
"""

df_11 = df[cond_11]

df_11.info()

df_11['total_count'].sum()

"""R.: Foram realizadas 1.243.103 alocações em 2011.

g. Quantas locações de bicicletas foram efetuadas em 2012?
"""

df_12 = df[cond_12]

df_12['total_count'].sum()

"""R.: Foram realizadas 2.049.576 alocações em 2012.

h. Qual estação do ano contém a maior média de locações de bicicletas?
"""

df[['season', 'total_count']].groupby(by='season').mean().sort_values('total_count')

"""R.: Verão (3)

i. Qual estação do ano contém a menor média de locações de bicicletas?

R.: Inverno (1)

j. Qual horário do dia contém a maior média de locações de bicicletas?
"""

df[['hour', 'total_count']].groupby(by='hour').mean().sort_values('total_count')

"""R.: Às 17 horas

k. Qual horário do dia contém a menor média de locações de bicicletas?

R.: Às 4 horas

l. Que dia da semana contém a maior média de locações de bicicletas?
"""

df[['weekday', 'total_count']].groupby(by='weekday').mean().sort_values('total_count')

"""R.: Às quintas-feiras (4).

m. Que dia da semana contém a menor média de locações de bicicletas?

R.: Aos domingos (0).

n. Às quartas-feiras (weekday = 3), qual o horário do dia contém a maior média de locações de bicicletas?
"""

cond_4f= df.weekday == 3
df_4f = df[cond_4f]

df_4f[['hour', 'total_count']].groupby(by='hour').mean().sort_values('total_count')

"""R.: Às 17 horas.

o. Aos sábados (weekday = 6), qual o horário do dia contém a maior média de locações de bicicletas?
"""

cond_sab= df.weekday == 6
df_sab = df[cond_sab]

df_sab[['hour', 'total_count']].groupby(by='hour').mean().sort_values('total_count')

"""R.: Às 13 horas."""